version: 2
updates:
  - package-ecosystem: maven
    directory: "/Framework/"
    target-branch: "pre-main"
    rebase-strategy: "auto"
    schedule:
      interval: daily
      time: '06:00'
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 99

  - package-ecosystem: maven
    directory: "/AssessmentProj/"
    target-branch: "pre-main"
    rebase-strategy: "auto"
    schedule:
      interval: daily
      time: '06:00'
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "pre-main"
    rebase-strategy: "auto"
    schedule:
      interval: weekly
      time: '06:00'
      timezone: "Australia/Sydney"
    open-pull-requests-limit: 99